name: CI - Lint YAML

on:
  pull_request:
    branches: ["main", "master"]
  push:
    branches: ["main", "master"]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: |
          python3 -m pip install --upgrade pip
          pip install yamllint
      - name: Lint
        run: yamllint .
