name: CI - Lint YML

on:
  pull_request:
    branches: ["main", "master"]
  push:
    branches: ["main", "master"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install yamllint
        run: |
          python3 -m pip install --upgrade pip
          pip install yamllint
      - name: Lint
        run: yamllint .
